In [1]:
import pandas
import numpy
import cv2

In [2]:
n=numpy.arange(27) #creates a range of numbers from 0-26
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [3]:
n.reshape(3,9) #reshapes n to form a 3x9 2D array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [4]:
m=numpy.asarray([[122,255,123,255],[],[]]) #creates an array from an existing list

In [5]:
m

array([list([122, 255, 123, 255]), list([]), list([])], dtype=object)

In [6]:
img=cv2.imread("smallgray.png",0) #the 0 is used to represent the image in grayscale

In [7]:
imgColor=cv2.imread("smallgray.png",1) #the 1 is used to represent the image in grayscale

In [8]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
imgColor #OpenCV uses BGR NOTE!!!

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [10]:
cv2.imwrite("NewSmallGray.png",imgColor) #creates an image using an array

True

In [12]:
#Start slicing the rows to target a specific pixel
img[0:2] #takes the first two rows

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [23]:
#To move to the column pixels we target the pixel area by removing columns
imgPixArea = img[0:2,2:4]
imgPixArea

array([[104, 121],
       [255, 255]], dtype=uint8)

In [24]:
#checking the shape of the array to make sure we are correct
imgPixArea.shape

(2, 2)

In [25]:
#If we wanted to check a single line (columns 2 & 3 are extracted from all 3 rows)
imgLine = img[:,2:4]
imgLine

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [29]:
#For checking a specific pixel (this is the 4th pixel in the first row)
imgPix = img[0,3]
imgPix

121

In [31]:
for i in img: #transverses through the array and prints each element
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [33]:
for i in img.T: #transverses through the TRANSPOSED array and prints each element
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [34]:
for i in img.flat: #transverse through each element linearly
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
